### ISSUE TITLE
beta6 crash when adjusting the playing video youtube setting

### ISSUE THREAD

**Issue by billborsari** [kas1e/Odyssey#11]
I've been able to verify this on two different youtube videos between reboots.

Odyssey Beta6, browser string set to default

Reproduction:
1) Open youtube
2) Launch video
3) Click the "gear"
4) Crash

Ignoring the DSI allows the setting to open and changing the quality works.

Crashed process: AppDir:Odyssey (0x67C0DB30)
DSI verbose error description: Access not allowed by page protection (protection violation)
Access was a load operation
 0: 7E303D44 64560530 00000002 63C19084 64560578 6456059C 007FFFFF 63C19084
 8: 80000000 00000000 80000000 00018F8C 39353453 64783110 00000000 00000000
16: 6456156C 645615AC 64561538 645615B4 00000000 00000000 616BD118 617B4F18
24: 617B4EE8 00000000 64788414 64560DF8 616BD1F0 00000000 5FD33948 63C19084
CR: 39353353   XER: C000006F  CTR: 7E31AF50  LR: 7E303D44
DSISR: 00800000  DAR: 63C190A4

FP0 : FFF80000B6E64100 BFEEE983E5A14765 4079148000000000 408218D800000000
FP4 : BFC2810EC73B6000 0000000000000000 407917C912BBBF5F 3F70000000000000
FP8 : 40821BAFEF138C4A 3FDA9F9DF2BA7EC8 3FF12912BBBF5F00 3FD0800000000000
FP12: 42B8000000024376 BFEBB55DEDCB3956 0098546C1386042E 1170010020AE8036
FP16: 100406813060812A F22119D4945E01F0 020448C105582A28 A0102C80080C65E5
FP20: 3408188445942080 BFE142281DC86460 A055029E86208098 884C47EB405802F4
FP24: 8302C8A4AD089E0B 8000080A00C8226E 471240C0020A02A8 584824C7065C8C02
FP28: A90220F8008D8836 FFA44055254D4E00 0F82053503A14C00 3FB999999999999A
FPSCR: B6E64100

Disassembly of crash site:
 7E303830: 7D295378   or                r9,r9,r10
 7E303834: 5529063E   rlwinm            r9,r9,0,24,31
 7E303838: 7D290034   cntlzw            r9,r9
 7E30383C: 5529D97E   rlwinm            r9,r9,27,5,31
>7E303840: 913F0020   stw               r9,32(r31)
 7E303844: 83E1003C   lwz               r31,60(r1)
 7E303848: 38210040   addi              r1,r1,64
 7E30384C: 4E800020   blr
 7E303850: 7C0802A6   mflr              r0
 7E303854: 90010044   stw               r0,68(r1)

Kernel command line: serial debuglevel=0

Registers pointing to code:
r0 : AppDir:Odyssey:_cairo_clip_intersect_box()+0x78 (section 1 @ 0x19B2D40)
r3 : AppDir:Odyssey:__cairo_clip_all()+0x0 (section 3 @ 0xE6080)
r7 : AppDir:Odyssey:__cairo_clip_all()+0x0 (section 3 @ 0xE6080)
r13: AppDir:Odyssey:_ZZN7WebCore9TextTrack24captionMenuAutomaticItemEvE9automatic()+0x0 (section 23 @ 0x537C)
r26: AppDir:Odyssey:spans.12878()+0x0 (section 23 @ 0xA680)
r31: AppDir:Odyssey:__cairo_clip_all()+0x0 (section 3 @ 0xE6080)
ip : AppDir:Odyssey:_cairo_clip_intersect_rectangle_box()+0x36c (section 1 @ 0x19B283C)
lr : AppDir:Odyssey:_cairo_clip_intersect_box()+0x78 (section 1 @ 0x19B2D40)
ctr: AppDir:Odyssey:close_path()+0x0 (section 1 @ 0x19C9F4C)

Stack trace:
(0x64560530) AppDir:Odyssey:_cairo_clip_intersect_rectangle_box()+0x36c (section 1 @ 0x19B283C)
(0x64560570) AppDir:Odyssey:_cairo_clip_intersect_box()+0x78 (section 1 @ 0x19B2D40)
(0x64560590) AppDir:Odyssey:_cairo_spans_compositor_stroke()+0x200 (section 1 @ 0x1A1ED54)
(0x645609A0) AppDir:Odyssey:_cairo_compositor_stroke()+0xdc (section 1 @ 0x1A0C58C)
(0x64560C80) AppDir:Odyssey:_cairo_image_surface_stroke()+0x40 (section 1 @ 0x19BB9B0)
(0x64560C90) AppDir:Odyssey:_cairo_surface_stroke()+0x150 (section 1 @ 0x19DF538)
(0x64560CE0) AppDir:Odyssey:_cairo_gstate_stroke()+0x100 (section 1 @ 0x19B88C4)
(0x64560E40) AppDir:Odyssey:_cairo_default_context_stroke()+0x24 (section 1 @ 0x19B3CD8)
(0x64560E50) AppDir:Odyssey:INT_cairo_stroke()+0x30 (section 1 @ 0x19AEE20)
(0x64560E60) AppDir:Odyssey:_ZN7WebCore15GraphicsContext10strokePathERKNS_4PathE()+0x120 (section 1 @ 0x161C0C)
(0x64560ED0) AppDir:Odyssey:_ZNK7WebCore14RenderSVGShape11strokeShapeEPNS_15GraphicsContextE()+0x58 (section 1 @ 0x129B16C)
(0x64560F20) AppDir:Odyssey:_ZNK7WebCore13RenderSVGPath11strokeShapeEPNS_15GraphicsContextE()+0x8c (section 1 @ 0x128A49C)
(0x64560FC0) AppDir:Odyssey:_ZN7WebCore27RenderSVGResourceSolidColor17postApplyResourceEPNS_12RenderObjectERPNS_15GraphicsContextEtPKNS_4PathEPKNS_14RenderSVGShapeE()+0x108 (section 1 @ 0x129A508)
(0x64560FE0) AppDir:Odyssey:_ZN7WebCore14RenderSVGShape11strokeShapeEPNS_11RenderStyleEPNS_15GraphicsContextE()+0xb4 (section 1 @ 0x129B788)
(0x64561020) AppDir:Odyssey:_ZN7WebCore14RenderSVGShape18fillAndStrokeShapeEPNS_15GraphicsContextE()+0xe8 (section 1 @ 0x129B914)
(0x64561080) AppDir:Odyssey:_ZN7WebCore14RenderSVGShape5paintERNS_9PaintInfoERKNS_11LayoutPointE()+0x31c (section 1 @ 0x129C6D8)
(0x64561140) AppDir:Odyssey:_ZN7WebCore18RenderSVGContainer5paintERNS_9PaintInfoERKNS_11LayoutPointE()+0x1d8 (section 1 @ 0x1284740)
(0x64561210) AppDir:Odyssey:_ZN7WebCore9RenderBox5paintERNS_9PaintInfoERKNS_11LayoutPointE()+0xc8 (section 1 @ 0x787B2C)
(0x64561270) AppDir:Odyssey:_ZN7WebCore13RenderSVGRoot13paintReplacedERNS_9PaintInfoERKNS_11LayoutPointE()+0x2f4 (section 1 @ 0x8F0E40)
(0x645613A0) AppDir:Odyssey:_ZN7WebCore14RenderReplaced5paintERNS_9PaintInfoERKNS_11LayoutPointE()+0x934 (section 1 @ 0x870AB0)
(0x64561450) AppDir:Odyssey:_ZN7WebCore11RenderLayer36paintForegroundForFragmentsWithPhaseENS_10PaintPhaseERKN3WTF6VectorINS_13LayerFragmentELj1ENS2_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEjPNS_12RenderObjectE()+0x1c0 (section 1 @ 0x815A08)
(0x645614E0) AppDir:Odyssey:_ZN7WebCore11RenderLayer27paintForegroundForFragmentsERKN3WTF6VectorINS_13LayerFragmentELj1ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextES9_RKNS_10LayoutRectEbRKNS0_17LayerPaintingInfoEjPNS_12RenderObjectEbb()+0x1f4 (section 1 @ 0x81DDF0)
(0x64561520) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x988 (section 1 @ 0x829574)
(0x645616B0) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x645616D0) AppDir:Odyssey:_ZN7WebCore11RenderLayer29paintLayerByApplyingTransformEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEjRKNS_11LayoutPointE()+0x214 (section 1 @ 0x829A98)
(0x64561870) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x2f8 (section 1 @ 0x82A160)
(0x64561960) AppDir:Odyssey:_ZN7WebCore11RenderLayer9paintListEPN3WTF6VectorIPS0_Lj0ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x84 (section 1 @ 0x82B4C4)
(0x64561990) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x440 (section 1 @ 0x82902C)
(0x64561B20) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x64561B40) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0xf4 (section 1 @ 0x829F5C)
(0x64561C30) AppDir:Odyssey:_ZN7WebCore11RenderLayer9paintListEPN3WTF6VectorIPS0_Lj0ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x84 (section 1 @ 0x82B4C4)
(0x64561C60) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x440 (section 1 @ 0x82902C)
(0x64561DF0) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x64561E10) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0xf4 (section 1 @ 0x829F5C)
(0x64561F00) AppDir:Odyssey:_ZN7WebCore11RenderLayer9paintListEPN3WTF6VectorIPS0_Lj0ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x84 (section 1 @ 0x82B4C4)
(0x64561F30) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x440 (section 1 @ 0x82902C)
(0x645620C0) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x645620E0) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0xf4 (section 1 @ 0x829F5C)
(0x645621D0) AppDir:Odyssey:_ZN7WebCore11RenderLayer9paintListEPN3WTF6VectorIPS0_Lj0ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x84 (section 1 @ 0x82B4C4)
(0x64562200) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x440 (section 1 @ 0x82902C)
(0x64562390) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x645623B0) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0xf4 (section 1 @ 0x829F5C)
(0x645624A0) AppDir:Odyssey:_ZN7WebCore11RenderLayer9paintListEPN3WTF6VectorIPS0_Lj0ENS1_15CrashOnOverflowEEEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x84 (section 1 @ 0x82B4C4)
(0x645624D0) AppDir:Odyssey:_ZN7WebCore11RenderLayer18paintLayerContentsEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x440 (section 1 @ 0x82902C)
(0x64562660) AppDir:Odyssey:_ZN7WebCore11RenderLayer31paintLayerContentsAndReflectionEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0x74 (section 1 @ 0x829820)
(0x64562680) AppDir:Odyssey:_ZN7WebCore11RenderLayer10paintLayerEPNS_15GraphicsContextERKNS0_17LayerPaintingInfoEj()+0xf4 (section 1 @ 0x829F5C)
(0x64562770) AppDir:Odyssey:_ZN7WebCore11RenderLayer5paintEPNS_15GraphicsContextERKNS_10LayoutRectEjPNS_12RenderObjectEPNS_12RenderRegionEj()+0xe4 (section 1 @ 0x82A280)
(0x64562800) AppDir:Odyssey:_ZN7WebCore9FrameView13paintContentsEPNS_15GraphicsContextERKNS_7IntRectE()+0x23c (section 1 @ 0x6C4570)
(0x64562860) AppDir:Odyssey:_ZN7WebCore10ScrollView5paintEPNS_15GraphicsContextERKNS_7IntRectE.part.21()+0x2b8 (section 1 @ 0x1EE470)
(0x64562910) AppDir:Odyssey:_ZN7WebCore10ScrollView5paintEPNS_15GraphicsContextERKNS_7IntRectE()+0x94 (section 1 @ 0x1F0EEC)
(0x64562930) AppDir:Odyssey:_ZN14WebViewPrivate8onExposeEi()+0x4e8 (section 1 @ 0xDE200)
(0x64562A80) AppDir:Odyssey:_ZN7WebView8onExposeEi()+0x48 (section 1 @ 0xBB228)
(0x64562AA0) AppDir:Odyssey:_ZL22handleMM_OWBApp_ExposeP6IClassPmP4_Msg()+0x1f4 (section 1 @ 0x5258)
(0x64562B00) AppDir:Odyssey:_ZL8dispatchP6IClassPmP4_Msg()+0x112c (section 1 @ 0x11040)
(0x64562B40) native kernel module intuition.library.kmod+0x00020288
(0x64562BA0) native kernel module intuition.library.kmod+0x00021578
(0x64562C20) native kernel module intuition.library.kmod+0x0000a568
(0x64562C90) AppDir:Odyssey:_Z9main_loopv()+0x1b4 (section 1 @ 0x1AF0)
(0x64562CE0) AppDir:Odyssey:main()+0x1d0 (section 1 @ 0x1D58)
(0x64562D20) native kernel module newlib.library.kmod+0x000025fc
(0x64562D70) native kernel module newlib.library.kmod+0x00003328
(0x64562F20) native kernel module newlib.library.kmod+0x0000384c
(0x64562F50) AppDir:Odyssey:_start()+0x170 (section 1 @ 0x214)
(0x64562F90) native kernel module dos.library.kmod+0x0002a41c
(0x64562FC0) native kernel module kernel+0x000594ac
(0x64562FD0) native kernel module kernel+0x000594f4

Disassembly of crash site:
 7E303830: 7D295378   or                r9,r9,r10
 7E303834: 5529063E   rlwinm            r9,r9,0,24,31
 7E303838: 7D290034   cntlzw            r9,r9
 7E30383C: 5529D97E   rlwinm            r9,r9,27,5,31
>7E303840: 913F0020   stw               r9,32(r31)
 7E303844: 83E1003C   lwz               r31,60(r1)
 7E303848: 38210040   addi              r1,r1,64
 7E30384C: 4E800020   blr
 7E303850: 7C0802A6   mflr              r0
 7E303854: 90010044   stw               r0,68(r1)
Stack pointer (0x64562FE0) is inside bounds
Redzone is OK (4)

68k register dump
DATA: 00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000
----> 00000001 - "LIBS:mui/Lamp.mcc" Hunk 0000 Offset 00000000 (SegList: 0x18CFD9A5)
ADDR: 6A3BBD4E 6A3BEF14 00000000 00000000 00000000 00000000 00000000 64561E70
Page information:
Page 0xEFC6E300:
Virtual Address: 0x63C19000
Physical Address: 0x0EAE6000
Lock count: 1
Flags (0x102): (Swappable) (Mapped)
Protection bits (0x0): (super state only)
Page is assigned to VMArea primary heap

**Comment by kas1e** [comment]
Yeah, there already a bug report for it: https://github.com/kas1e/Odyssey/issues/6 , so merge that report with the earlier one.
