### ISSUE TITLE
Enhancement - Support for extended mouse buttons  

### ISSUE THREAD

**Issue by nbache** [kas1e/Odyssey#15]
(This was issue 630 on the old OS4Depot bug tracker, created by Cyborg at 20110927 09:18, and supported by Lio)

"It  would be very nice if mouse buttons 4 and 5 would be supported for  stepping forward and backward through the browser history. Even IBrowse  supports that :)"

And I also second this.

**Comment by kas1e** [comment]
Added, will be avail in beta07
