### ISSUE TITLE
RC5: Reproducable crash in cairo

### ISSUE THREAD

**Issue by raziel-** [kas1e/Odyssey#6]
Spoof with IPad6.1

1) Go to https://www.scummvm.org
2) Scroll down (mouse wheel) the page

I never reach the end of the main oage, it crashes bveforehand every single time
[Crashlog_Odyssey_2020-04-03_20-29-39.txt](https://github.com/kas1e/Odyssey/files/4429302/Crashlog_Odyssey_2020-04-03_20-29-39.txt)
[Crashlog_Odyssey_2020-04-03_20-31-27.txt](https://github.com/kas1e/Odyssey/files/4429303/Crashlog_Odyssey_2020-04-03_20-31-27.txt)

**Comment by balxavier** [comment]
Hi,

I've got the same sort of crash when I browse morph.zone using the last beta version.

Regards,

**Comment by kas1e** [comment]
Fixed in beta07
