### ISSUE TITLE
Mute and Unmute option in menu

### ISSUE THREAD

**Issue by samo79** [kas1e/Odyssey#9]
There is probably a bug in the video menu handling the switch between the "Mute" and "Unmute" options.
Both options are availible in the owb.cd so it should be supposed to work.
As a direct reference see how Play and Pause are handled in the same menu

**Comment by kas1e** [comment]
Fixed in https://github.com/kas1e/Odyssey/commit/e546ddcd01b18b9b469a8e1222d7ae6f600b0629

Through fixed to be it not like Play/Pause, but just like Control and Loop items (so it just has marker item). That was much easier as code was there already, just wasn't enabled because of a typo.
